---

- name: remove cloud-init network configuration file
  file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent
  become: yes

- name: create network configuration file
  template:
    src: templates/netplan-static-ip.yaml.j2
    dest: /etc/netplan/60-static-ip.yaml
  become: yes
  register: netplan_template

- name: apply network configuration
  shell: "(sleep 1;netplan apply) &"
  async: 15
  poll: 0
  become: yes
  when: netplan_template is changed

- name: use static IP address
  set_fact:
    ansible_ssh_host: "{{ static_ipv4 }}"
  changed_when: vm_facts.instance.ipv4 != static_ipv4
  when: netplan_template is changed

- meta: reset_connection

- name: ensure IP address is reachable
  wait_for_connection:
    connect_timeout: 3
    timeout: 30

# vim: ts=2:sw=2:noautoindent:nosmartindent
